name: Jobs
description: Bukkit 职业插件
main: me.zford.jobs.bukkit.JobsPlugin
version: ${build.version}
author: phrstbrn
softdepend: [Vault]
commands:
  jobs:
    description: 职业插件相关指令
    usage: /jobs
permissions:
  jobs.*:
    description: 职业插件全部权限
    children:
      jobs.admin: true
  jobs.admin:
    description: 职业插件管理员权限
    default: false
    children:
      jobs.use: true
      jobs.command.*: true
  jobs.use:
    description: 职业插件使用权限
    default: true
  jobs.command.*:
    description: 职业插件全部指令权限
    default: false
    children:
      jobs.command.browse: true
      jobs.command.stats: true
      jobs.command.admin.stats: true
      jobs.command.join: true
      jobs.command.leave: true
      jobs.command.leaveall: true
      jobs.command.info: true
      jobs.command.playerinfo: true
      jobs.command.fire: true
      jobs.command.fireall: true
      jobs.command.employ: true
      jobs.command.promote: true
      jobs.command.demote: true
      jobs.command.grantxp: true
      jobs.command.removexp: true
      jobs.command.transfer: true
      jobs.command.reload: true
      jobs.command.help: true
  jobs.command.browse:
    description: 职业插件浏览指令权限
    default: true
  jobs.command.stats:
    description: 职业插件状态指令使用权限
    default: true
  jobs.command.admin.stats:
    description: 职业插件全部状态指令使用权限
    default: true
  jobs.command.join:
    description: 职业插件入职指令使用权限
    default: true
  jobs.command.leave:
    description: 职业插件离职指令使用权限
    default: true
  jobs.command.leaveall:
    description: 职业插件全部离职指令使用权限
    default: true
  jobs.command.info:
    description: 职业插件信息指令使用权限
    default: true
  jobs.command.playerinfo:
    description: 职业插件玩家信息指令使用权限
    default: op
  jobs.command.fire:
    description: 职业插件开除指令使用权限
    default: op
  jobs.command.fireall:
    description: 职业插件全部开除指令使用权限
    default: op
  jobs.command.employ:
    description: 职业插件采用指令使用权限
    default: op
  jobs.command.promote:
    description: 职业插件升值指令使用权限
    default: op
  jobs.command.demote:
    description: 职业插件降职指令使用权限
    default: op
  jobs.command.grantxp:
    description: 职业插件提升经验指令使用权限
    default: op
  jobs.command.removexp:
    description: 职业插件降低经验指令使用权限
    default: op
  jobs.command.transfer:
    description: 职业插件转让指令使用权限
    default: op
  jobs.command.reload:
    description: 职业插件重新载入指令使用权限
    default: op
  jobs.command.help:
    description: 职业插件帮助指令使用权限
    default: true  